<!doctype html>
<html>
<head>
    <meta charset=utf-8>
    <title>Small RESTful web service</title>
</head>
<body>
<pre>
*** RESTful web service ***

Response body format: JSON

Endpoints:
/       - this help
/login/ - user auth
/users/ - users list (requires authentication)
/logs/  - request logs (requires authentication)

To access /users/ and /logs/ you should provide secret token with special HTTP Header: HTTP_X_TOKEN

Use this endpoint to get token value for all other calls:

POST /login/ - login
body: { "email": "admin@example.com", "password": "admin" }
$ curl -X POST -d '{ "email":"admin@example.com", "password": "admin" }' <?= $this->url('/login/') ?> 
response: 200
{
    "success": true,
    "session_token": "{token}"
}

*** Users ***

GET /users/ - get list of all users
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl <?= $this->url('/users/') ?> -H 'HTTP_X_TOKEN: {token}'
response: 200
{ "users":[...], "total":15 }

GET /users/{id} - get user with specified id
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl <?= $this->url('/users/{id}') ?> -H 'HTTP_X_TOKEN: {token}'
response: 200
{
    "user": {
        "id": 1,
        "email": "e-moe@ukr.net"
    }
}

POST   /users/     - create new
PUT    /users/{id} - create new or update existing
DELETE /users/{id} - delete user with specified id
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email":"admin@example.com", "password": "admin" }
$ curl -X METHOD -d '{ "email":"admin@example.com", "password": "admin" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 200, 201, 204
{
  "success":true,
  "url":"/users/{id}"
}

*** Validation Errors ***

PUT  /users/{id} - create new or update existing
POST /users/  - create new
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email": "test6@example.com" }
$ curl -X METHOD -d '{ "email": "test6@example.com" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 400
{ 
    "errors": [ "Missed required field 'password'" ],
    "total":1
}

PUT  /users/3 - create new or update existing
POST /users/  - create new
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email": "notEmail", "password": "test" }
$ curl -X METHOD -d '{ "email": "notEmail", "password": "test" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 400
{
    "errors": [ "Field 'email' must be valid email address" ],
    "total":1
}

*** Logs ***

GET /logs/ - get list of all logs
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl <?= $this->url('/logs/') ?> -H 'HTTP_X_TOKEN: {token}'
response: 200
{ "logs":[...], "total":15 }

DELETE /logs/ - delete all logs
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl -X DELETE <?= $this->url('/logs/') ?> -H 'HTTP_X_TOKEN: {token}'
body: empty
response: 204 empty
    </pre>
</body>
</html>