<!doctype html>
<html>
<head>
    <meta charset=utf-8>
    <title>Small RESTful web service</title>
</head>
<body>
<pre>
*** RESTful web service ***

Response body format: JSON


*** Users ***

GET /users/ - get list of all users
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl <?= $this->url('/users/') ?> -H 'HTTP_X_TOKEN: {token}'
response: 200
{ "users":[...], "total":15 }

GET /users/{id} - get user with specified id
headers: HTTP_X_TOKEN = "token" (see POST /login/)
$ curl <?= $this->url('/users/{id}') ?> -H 'HTTP_X_TOKEN: {token}'
response: 200
{
    "id": 1,
    "email": "admin@example.com",
    "password": "admin"
}

POST   /users/     - create new
PUT    /users/{id} - create new or update existing
DELETE /users/{id} - delete user with specified id
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email":"admin@example.com", "password": "admin" }
$ curl -X METHOD -d '{ "email":"admin@example.com", "password": "admin" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 200, 201, 204, 400, 404
headers: Location

*** Validation Errors ***

PUT  /users/{id} - create new or update existing
POST /users/  - create new
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email": "test6@example.com" }
$ curl -X METHOD -d '{ "email": "test6@example.com" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 400
{ 
    "errors": [ "Missed required field 'password'" ],
    "total":1
}

PUT  /users/3 - create new or update existing
POST /users/  - create new
headers: HTTP_X_TOKEN = "token" (see POST /login/)
body: { "email": "notEmail", "password": "test" }
$ curl -X METHOD -d '{ "email": "notEmail", "password": "test" }' <?= $this->url('/users/{id}') ?>  -H 'HTTP_X_TOKEN: {token}'
response: 400
{
    "errors": [ "Field 'email' must be valid email address" ],
    "total":1
}
    </pre>
</body>
</html>